package by.epam.training.kazieva.connect;

import org.apache.log4j.Logger;

import java.sql.*;
import java.util.Properties;

public class WrapperConnection {
    private static final Logger logger = Logger.getLogger(WrapperConnection.class);
    private Connection connection;

    WrapperConnection() {
        String url = "jdbc:mysql://localhost:3306/mmf";
        String user = "admin";
        String pass = "admin";
        Properties properties = new Properties();
        properties.put("user", user);
        properties.put("password", pass);
        properties.put("autoReconnect", "true");
        properties.put("characterEncoding", "UTF-8");
        properties.put("useUnicode", "true");

        try {
            connection = DriverManager.getConnection(url, properties);
        } catch (SQLException e) {
            logger.error(e);
        }
    }

    public Statement getStatement() throws SQLException {
        if (connection != null) {
            Statement statement = null;
            try {
                statement = connection.createStatement();
            } catch (SQLException e) {
                logger.error(e);
            }
            if (statement != null) {
                return statement;
            }
        }
        throw new SQLException("connection or statement is null");
    }

    public void closeStatement(Statement statement) {
        if (statement != null) {
            try {
                statement.close();
            } catch (SQLException e) {
                logger.error("statement is null ", e);
            }
        }
    }
    void closeConnection() {
        if (connection != null) {
            try {
                connection.close();
            } catch (SQLException e) {
                logger.error("wrong connection", e);
            }
        }
    }


    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return connection.prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability);
    }


    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return connection.prepareStatement(sql, autoGeneratedKeys);
    }

    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return connection.prepareStatement(sql, columnIndexes);
    }

    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return connection.prepareStatement(sql, columnNames);
    }

    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return connection.prepareStatement(sql, resultSetType, resultSetConcurrency);
    }
}
